import { invoke } from "@tauri-apps/api/core";
export type Overview = { todayTokens:number; monthTokens:number; updatedAt:string; balance:string|null; sourceStatus:string };
export type Source = { id:string; name:string; kind:string; enabled:boolean; selected:boolean; status:string };
export type SourceConfig = { id:string; name:string; kind:"deepseek"|"openai_compatible"|"newapi"|"script"; enabled:boolean; config:Record<string, unknown> };
export type Settings = { refreshMinutes:number; launchAtLogin:boolean; quietHoursEnabled:boolean };
export type Schedule = { intervalMinutes:number; retryCount:number; enabled:boolean };
export type DeviceConfig = { id:string; name:string; width:number; height:number; colorLayers:number; driverId:number; mtu:number; blockSize:number };
export type BleDevice = { id:string; name:string; rssi:number|null };
export type BleGattCharacteristic = { serviceUuid:string; uuid:string; properties:string };
export type BleConnectionInfo = { id:string; name:string; connected:boolean; characteristicCount:number; characteristics:BleGattCharacteristic[]; epdControlCharacteristic:string|null; firmwareVersion:number|null };
export type TransferResult = { deviceId:string; blocksSent:number; retryRounds:number; refreshed:boolean; connected:boolean; firmwareVersion:number|null; transferMode:"crc"|"legacy"; mtu:number; blockSize:number; driverId:number };
export type LogEntry = { id:number; occurredAt:string; level:"info"|"error"|string; action:string; message:string; details:string|null };
export type LogPage = { items:LogEntry[]; page:number; pageSize:number; total:number; totalPages:number };
export const api = {
  overview:()=>invoke<Overview>("get_overview"),sources:()=>invoke<Source[]>("list_sources"),sourceConfigs:()=>invoke<SourceConfig[]>("list_source_configs"),saveSource:(source:Source)=>invoke<void>("save_source",{source}),saveSourceConfig:(source:SourceConfig)=>invoke<void>("save_source_config",{source}),saveSourceSecret:(sourceId:string,secretRef:string,secret:string)=>invoke<void>("save_source_secret",{sourceId,secretRef,secret}),testSource:(sourceId:string)=>invoke<string>("test_source",{sourceId}),testSourceConfig:(source:SourceConfig,apiKey?:string)=>invoke<string>("test_source_config",{source,apiKey:apiKey ?? null}),deleteSource:(id:string)=>invoke<void>("delete_source",{id}),selectSource:(id:string)=>invoke<Source>("select_source",{id}),sync:()=>invoke<string>("sync_and_push"),preview:()=>invoke<string>("preview_dashboard"),scanDevices:()=>invoke<BleDevice[]>("scan_devices"),connectDevice:(deviceId:string)=>invoke<BleConnectionInfo>("connect_device",{deviceId}),autoConnectLastDevice:()=>invoke<BleConnectionInfo|null>("auto_connect_last_device"),disconnectDevice:(deviceId:string)=>invoke<boolean>("disconnect_device",{deviceId}),pushEpdTestImage:(deviceId:string,config:DeviceConfig)=>invoke<TransferResult>("push_epd_test_image",{deviceId,config}),deviceConfig:()=>invoke<DeviceConfig>("get_device_config"),saveDeviceConfig:(config:DeviceConfig)=>invoke<DeviceConfig>("save_device_config",{config}),prepareTransfer:(config:DeviceConfig)=>invoke<number>("prepare_epd_transfer",{config}),schedule:()=>invoke<Schedule>("get_schedule"),saveSchedule:(schedule:Schedule)=>invoke<Schedule>("save_schedule",{schedule}),scheduleIsDue:()=>invoke<boolean>("schedule_is_due"),settings:()=>invoke<Settings>("get_settings"),saveSettings:(settings:Settings)=>invoke<Settings>("save_settings",{settings}),setAutostart:(enabled:boolean)=>invoke<boolean>("set_autostart",{enabled}),
  logs:(page=1,pageSize=50)=>invoke<LogPage>("list_logs",{page,pageSize}),
};
